# Loading Dataset

In [32]:
import pandas as pd

In [33]:
df=pd.read_csv('../datasets/olist_master_dataset.csv')
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'total_payment_value', 'payment_installments', 'payments_method_count',
       'primary_payment_type', 'review_score', 'review_comment_title',
       'review_comment_message', 'product_category', 'is_delivered'],
      dtype='object')

# Getting items per order

In [34]:
items_per_order = df.groupby('order_id').size().reset_index(name='num_items')

In [35]:
df1 = df.merge(items_per_order, on='order_id', how='left')

In [36]:
df1

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,total_payment_value,payment_installments,payments_method_count,primary_payment_type,review_score,review_comment_title,review_comment_message,product_category,is_delivered,num_items
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,38.71,3.0,2.0,credit_card,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",housewares,1,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,141.46,1.0,1.0,boleto,4.0,Muito boa a loja,Muito bom o produto.,perfumery,1,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,179.12,3.0,1.0,credit_card,5.0,NaN,NaN,auto,1,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,...,72.20,1.0,1.0,credit_card,5.0,NaN,O produto foi exatamente o que eu esperava e e...,pet_shop,1,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,...,28.62,1.0,1.0,credit_card,5.0,NaN,NaN,stationery,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113309,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,195.00,3.0,1.0,credit_card,4.0,NaN,So uma peça que veio rachado mas tudo bem rs,baby,1,1
113310,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,...,271.01,5.0,1.0,credit_card,5.0,NaN,Foi entregue antes do prazo.,home_appliances_2,1,1
113311,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,441.16,4.0,1.0,credit_card,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,computers_accessories,1,2
113312,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,441.16,4.0,1.0,credit_card,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,computers_accessories,1,2
113313,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,...,86.86,1.0,1.0,debit_card,5.0,NaN,NaN,health_beauty,1,1

# Getting frequency

In [37]:
frequency=df1.groupby('customer_unique_id')['order_id'].nunique().reset_index(name='num_of_orders')

In [38]:
frequency

                     customer_unique_id  num_of_orders
0      0000366f3b9a7992bf8c76cfdf3221e2              1
1      0000b849f77a49e4a4ce2b2a4ca5be3f              1
2      0000f46a3911fa3c0805444483337064              1
3      0000f6ccb0745a6a4b88665a16c9f078              1
4      0004aac84e0df4da2b147fca70cf8255              1
...                                 ...            ...
95415  fffcf5a5ff07b0908bd4e2dbc735a684              1
95416  fffea47cd6d3cc0a88bd621562a9d061              1
95417  ffff371b4d645b6ecea244b27531430a              1
95418  ffff5962728ec6157033ef9805bacc48              1
95419  ffffd2657e2aad2907e67c3e9daecbeb              1

[95420 rows x 2 columns]

# Getting Monetary

In [39]:
monetary=df1.groupby('customer_unique_id')['total_payment_value'].sum().reset_index(name='total_payment')

In [40]:
monetary

                     customer_unique_id  total_payment
0      0000366f3b9a7992bf8c76cfdf3221e2         141.90
1      0000b849f77a49e4a4ce2b2a4ca5be3f          27.19
2      0000f46a3911fa3c0805444483337064          86.22
3      0000f6ccb0745a6a4b88665a16c9f078          43.62
4      0004aac84e0df4da2b147fca70cf8255         196.89
...                                 ...            ...
95415  fffcf5a5ff07b0908bd4e2dbc735a684        4134.84
95416  fffea47cd6d3cc0a88bd621562a9d061          84.58
95417  ffff371b4d645b6ecea244b27531430a         112.46
95418  ffff5962728ec6157033ef9805bacc48         133.69
95419  ffffd2657e2aad2907e67c3e9daecbeb          71.56

[95420 rows x 2 columns]

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113314 entries, 0 to 113313
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113314 non-null  object
 1   customer_id                    113314 non-null  object
 2   order_status                   113314 non-null  object
 3   order_purchase_timestamp       113314 non-null  object
 4   order_approved_at              113314 non-null  object
 5   order_delivered_carrier_date   112111 non-null  object
 6   order_delivered_customer_date  110839 non-null  object
 7   order_estimated_delivery_date  113314 non-null  object
 8   order_item_id                  113314 non-null  int64
 9   product_id                     113314 non-null  object
 10  seller_id                      113314 non-null  object
 11  shipping_limit_date            113314 non-null  object
 12  price                          113314 non-null  float64
 13  freight_value                  113314 non-null  float64
 14  customer_unique_id             113314 non-null  object
 15  customer_zip_code_prefix       113314 non-null  int64
 16  customer_city                  113314 non-null  object
 17  customer_state                 113314 non-null  object
 18  total_payment_value            113314 non-null  float64
 19  payment_installments           113314 non-null  float64
 20  payments_method_count          113314 non-null  float64
 21  primary_payment_type           113314 non-null  object
 22  review_score                   113314 non-null  float64
 23  review_comment_title           13434 non-null   object
 24  review_comment_message         47642 non-null   object
 25  product_category               113314 non-null  object
 26  is_delivered                   113314 non-null  int64
 27  num_items                      113314 non-null  int64
dtypes: float64(6), int64(4), object(18)
memory usage: 24.2+ MB

# Computing avg delay,avg delivery time,delivery fail rate

In [42]:
df1['order_delivered_customer_date']=pd.to_datetime(df1['order_delivered_customer_date'])
df1['order_purchase_timestamp']=pd.to_datetime(df1['order_purchase_timestamp'])

In [43]:
df1['order_estimated_delivery_date']=pd.to_datetime(df1['order_estimated_delivery_date'])

In [44]:
df1['delivery_time_days'] = (
    df1['order_delivered_customer_date'] - df1['order_purchase_timestamp']
).dt.days

In [45]:
df1['delivery_delay_days'] = (
    df1['order_delivered_customer_date'] - df1['order_estimated_delivery_date']
).dt.days

In [46]:
avg_delivery_time = df1.groupby('customer_unique_id')['delivery_time_days'].mean().reset_index(name='avg_delivery_time')

In [47]:
avg_delay = df1.groupby('customer_unique_id')['delivery_delay_days'].mean().reset_index(name='avg_delivery_delay')

In [48]:
delivery_fail_rate = df.groupby('customer_unique_id')['is_delivered'].mean().reset_index(name='delivery_success_rate')

delivery_fail_rate['delivery_fail_rate'] = 1 - delivery_fail_rate['delivery_success_rate']

# Calculating Recency

In [49]:
max_date=df1['order_purchase_timestamp'].max()

In [50]:
recency=df1.groupby('customer_unique_id')['order_purchase_timestamp'].max().reset_index(name='last_purchase_date')

In [51]:
recency['last_purchase_date']=pd.to_datetime(recency['last_purchase_date'])

In [52]:
recency['recency_days']=(max_date-recency['last_purchase_date']).dt.days

In [53]:
recency

                     customer_unique_id  last_purchase_date  recency_days
0      0000366f3b9a7992bf8c76cfdf3221e2 2018-05-10 10:56:27           115
1      0000b849f77a49e4a4ce2b2a4ca5be3f 2018-05-07 11:11:27           118
2      0000f46a3911fa3c0805444483337064 2017-03-10 21:05:03           541
3      0000f6ccb0745a6a4b88665a16c9f078 2017-10-12 20:29:41           325
4      0004aac84e0df4da2b147fca70cf8255 2017-11-14 19:45:42           292
...                                 ...                 ...           ...
95415  fffcf5a5ff07b0908bd4e2dbc735a684 2017-06-08 21:00:36           451
95416  fffea47cd6d3cc0a88bd621562a9d061 2017-12-10 20:07:56           266
95417  ffff371b4d645b6ecea244b27531430a 2017-02-07 15:49:16           572
95418  ffff5962728ec6157033ef9805bacc48 2018-05-02 15:17:41           123
95419  ffffd2657e2aad2907e67c3e9daecbeb 2017-05-02 20:18:45           488

[95420 rows x 3 columns]

# Computing avg review Score

In [54]:
avg_review_score=df1.groupby('customer_unique_id')['review_score'].mean().reset_index(name='avg_score')

In [55]:
avg_review_score

                     customer_unique_id  avg_score
0      0000366f3b9a7992bf8c76cfdf3221e2        5.0
1      0000b849f77a49e4a4ce2b2a4ca5be3f        4.0
2      0000f46a3911fa3c0805444483337064        3.0
3      0000f6ccb0745a6a4b88665a16c9f078        4.0
4      0004aac84e0df4da2b147fca70cf8255        5.0
...                                 ...        ...
95415  fffcf5a5ff07b0908bd4e2dbc735a684        5.0
95416  fffea47cd6d3cc0a88bd621562a9d061        4.0
95417  ffff371b4d645b6ecea244b27531430a        5.0
95418  ffff5962728ec6157033ef9805bacc48        5.0
95419  ffffd2657e2aad2907e67c3e9daecbeb        5.0

[95420 rows x 2 columns]

In [56]:
avg_items=df1.groupby('customer_unique_id')['num_items'].mean().reset_index(name='avg_items')

# Merging all the dataframes into single master customer dataframe

In [57]:
customer_df=(frequency
            .merge(monetary,on='customer_unique_id',how='left')
             .merge(recency[['customer_unique_id','recency_days']],on='customer_unique_id',how='left')
             .merge(avg_review_score,on='customer_unique_id',how='left')
             .merge(avg_items,on='customer_unique_id',how='left')
              .merge(avg_delivery_time, on='customer_unique_id', how='left')
              .merge(avg_delay, on='customer_unique_id', how='left')
             .merge(delivery_fail_rate[['customer_unique_id','delivery_fail_rate']], on='customer_unique_id', how='left')
            )

In [58]:
customer_df.head()

,customer_unique_id,num_of_orders,total_payment,recency_days,avg_score,avg_items,avg_delivery_time,avg_delivery_delay,delivery_fail_rate
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,115,5.0,1.0,6.0,-5.0,0.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,118,4.0,1.0,3.0,-5.0,0.0
2,0000f46a3911fa3c0805444483337064,1,86.22,541,3.0,1.0,25.0,-2.0,0.0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,325,4.0,1.0,20.0,-12.0,0.0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,292,5.0,1.0,13.0,-8.0,0.0

In [59]:
customer_df.isna().sum()

customer_unique_id       0
num_of_orders            0
total_payment            0
recency_days             0
avg_score                0
avg_items                0
avg_delivery_time     2064
avg_delivery_delay    2064
delivery_fail_rate       0
dtype: int64

In [60]:
customer_df['avg_delivery_time'] = customer_df['avg_delivery_time'].fillna(customer_df['avg_delivery_time'].median())
customer_df['avg_delivery_delay'] = customer_df['avg_delivery_delay'].fillna(0)

In [61]:
customer_df['churned']=(customer_df['num_of_orders']==1).astype(int)

In [62]:
customer_df.to_csv('../datasets/customer_df.csv',index=False)

In [63]:
customer_df.columns

Index(['customer_unique_id', 'num_of_orders', 'total_payment', 'recency_days',
       'avg_score', 'avg_items', 'avg_delivery_time', 'avg_delivery_delay',
       'delivery_fail_rate', 'churned'],
      dtype='object')

# Modeling the Logistic regression Model

In [64]:
from sklearn.model_selection import train_test_split as tts

In [65]:
X=customer_df[['total_payment', 'avg_score', 'avg_items',
       'avg_delivery_time', 'avg_delivery_delay', 'delivery_fail_rate']]

In [66]:
y=customer_df['churned']

In [67]:
X_train,X_test,y_train,y_test=tts(X,y,train_size=0.85,stratify=y)

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [69]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)

X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [70]:
logreg=LogisticRegression(class_weight='balanced',max_iter=500,solver='liblinear')

In [71]:
logreg.fit(X_train_res,y_train_res)

LogisticRegression(class_weight='balanced', max_iter=500, solver='liblinear')

In [72]:
y_proba = logreg.predict_proba(X_test)[:,1]
y_pred = (y_proba > 0.3).astype(int)

In [73]:
print(classification_report(y_test, y_pred, target_names=['retained','churned']))

              precision    recall  f1-score   support

    retained       0.09      0.14      0.11       437
     churned       0.97      0.95      0.96     13876

    accuracy                           0.93     14313
   macro avg       0.53      0.55      0.54     14313
weighted avg       0.95      0.93      0.94     14313

# Saving the Model

In [74]:
from joblib import dump

dump(logreg,'../backend/models/churn_prediction_model.joblib')

In [76]:
cust=pd.read_csv('../datasets/customer_df.csv')
cust.head(10)

,customer_unique_id,num_of_orders,total_payment,recency_days,avg_score,avg_items,avg_delivery_time,avg_delivery_delay,delivery_fail_rate,churned
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,115,5.0,1.0,6.0,-5.0,0.0,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,118,4.0,1.0,3.0,-5.0,0.0,1
2,0000f46a3911fa3c0805444483337064,1,86.22,541,3.0,1.0,25.0,-2.0,0.0,1
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,325,4.0,1.0,20.0,-12.0,0.0,1
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,292,5.0,1.0,13.0,-8.0,0.0,1
5,0004bd2a26a76fe21f786e4fbd80607f,1,166.98,150,4.0,1.0,1.0,-12.0,0.0,1
6,00050ab1314c0e55a6ca13cf7181fecf,1,35.38,135,4.0,1.0,6.0,-12.0,0.0,1
7,00053a61a98854899e70ed204dd4bafe,1,838.36,186,1.0,2.0,16.0,-10.0,0.0,1
8,0005e1862207bf6ccc02e4228effd9a0,1,150.12,547,4.0,1.0,4.0,-28.0,0.0,1
9,0005ef4cd20d2893f0d9fbd94d3c0d97,1,129.76,174,1.0,1.0,53.0,31.0,0.0,1

In [86]:
cust.loc[cust['num_of_orders']==16]

,customer_unique_id,num_of_orders,total_payment,recency_days,avg_score,avg_items,avg_delivery_time,avg_delivery_delay,delivery_fail_rate,churned
52597,8d50f5eadf50201ccdcedfb9e2ac8455,16,902.04,13,5.0,1.0,3.333333,-9.333333,0.0625,0

In [84]:
cust['num_of_orders'].unique()

array([ 1,  2,  3,  4,  6,  7,  5,  9, 16], dtype=int64)